name: Build NifSkope

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build_windows:
    runs-on: windows-latest
    name: Build MSYS2

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: 'Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        cache: true
        install: 'base-devel mingw-w64-ucrt-x86_64-gcc msys/p7zip mingw-w64-ucrt-x86_64-qt5-base mingw-w64-ucrt-x86_64-qt5-3d mingw-w64-ucrt-x86_64-qt5-imageformats mingw-w64-ucrt-x86_64-qt5-tools'

    - name: 'Build with qmake'
      shell: msys2 {0}
      run: |
        qmake noavx2=1 NifSkope.pro
        make -j 8
        mv -f release/NifSkope.exe release/NifSkope_noavx2.exe

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: build-win
        path: |
          release


  build_linux:
    runs-on: ubuntu-latest
    name: Build Linux

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: 'Install required packages'
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: libsdl2-dev qtbase5-dev qt5-qmake qt5-image-formats-plugins
          version: 1.0

    - name: 'Build with qmake'
      run: |
        x86_64-linux-gnu-qmake noavx2=1 NifSkope.pro
        make -j 8
        mv -f release/NifSkope release/NifSkope_noavx2

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: build-linux
        path: 'release'

  build_macos:
    runs-on: macos-latest
    name: Build MacOS

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: 'Install required packages'
      uses: jurplel/install-qt-action@v4

    - name: 'Install clang'
      run: brew install llvm

    - name: 'Build with qmake'
      run: |
        qmake noavx=1 NifSkope.pro
        make -j 8

    - name: 'Create DMG image'
      run: |
        cp release/*.xml release/NifSkope.app/Contents/MacOS/
        macdeployqt release/NifSkope.app -dmg

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: build-macos
        path: 'release'
